version: '3'
services:
  db:
    container_name: js-db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: js_db
      MYSQL_USER: jsuser
      MYSQL_PASSWORD: jspassword
    volumes:
      - "./database_vol:/var/lib/mysql"
  master:
    container_name: js-master
    image: arola1982/jobscheduler:latest
    environment:
      JAVABIN: /usr/local/openjdk-11/bin
      DB_HOST: js-db
      DB_SCHEMA: js_db
      DB_USER: jsuser
      DB_PASSWORD: jspassword
      JS_AGENTS: "agent1:js-agent1:4445,agent2:js-agent2:4445"
    build:
      context: .
    volumes:
      - "./master_vol:/opt/jobscheduler"
  joc:
    container_name: js-joc
    image: arola1982/jobscheduler-joc:latest
    environment:
      JAVABIN: /usr/local/openjdk-11/bin
      DB_HOST: js-db
      DB_SCHEMA: js_db
      DB_USER: jsuser
      DB_PASSWORD: jspassword
    build:
      context: joc/.
    ports:
      - "4446:4446"
    volumes:
      - "./joc_vol:/opt/joc"
  agent1:
    container_name: js-agent1
    image: arola1982/jobscheduler-agent:latest
    environment:
      JAVABIN: /usr/local/openjdk-11/bin
    build:
      context: agent/.
  agent2:
    container_name: js-agent2
    image: arola1982/jobscheduler-agent:latest
    environment:
      JAVABIN: /usr/local/openjdk-11/bin
    build:
      context: agent/.
